SetCVar("autoLootDefault", 1)
SetCVar("autoSelfCast", 1)
SetCVar("lootUnderMouse", 1)
SetCVar("screenshotQuality", 10)
SetCVar("showTutorials", 0)
SetCVar("ActionButtonUseKeyDown", 1)
SetCVar("autoQuestWatch", 1)
SetCVar("overrideArchive", 0)
SetCVar("ffxDeath ", 0)
SetCVar("ffxGlow", 0)
SetCVar("findYourselfModeOutline", 1)
SetCVar("UnitNamePlayerGuild", 0)